[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "Transmision"
version = "0.1"

[tool.hatch.build.targets.wheel]
packages = ["DomainConstruction", "FastMarching", "Operators"]